import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppGlobalProviders } from "./providers/AppGlobalProviders";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900"
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900"
});

export const metadata: Metadata = {
	title: "World Carbon mOnoxide Detector",
	description: "Generated by create next app",
	icons: {
		icon: [
			{ url: "/favicon.ico" },
			{ url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" }
		],
		apple: [
			{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }
		]
	}
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="it">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<AppGlobalProviders>{children}</AppGlobalProviders>
			</body>
		</html>
	);
}
