import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppGlobalProviders } from "./providers/AppGlobalProviders";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900"
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900"
});

export const metadata: Metadata = {
	title: "Global CO Detector",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: // menu
Readonly<{
	children: React.ReactNode;
	// menu: React.ReactNode;
}>) {
	return (
		<html lang="it">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				{/* {menu} */}
				<AppGlobalProviders>{children}</AppGlobalProviders>
			</body>
		</html>
	);
}
